name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
      - name: Flake Check
        run: ./.github/scripts/flake-check.sh
      - name: Lint Check
        run: nix shell nixpkgs#nixfmt nixpkgs#deadnix nixpkgs#statix -c ./.github/scripts/lint.sh