name: "Update All Flake Inputs"
on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: ./.github/workflows/reusable-flake-update-pipeline.yml
    with:
      update-command: 'nix flake update'
      branch-name: 'update-flake'
      pr-title: 'chore: update flake.lock'
    secrets:
      FLAKE_UPDATE_TOKEN: ${{ secrets.FLAKE_UPDATE_TOKEN }}